2023-05-19 19:48:30,106 DEBUG matplotlib matplotlib data path: C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\matplotlib\mpl-data
2023-05-19 19:48:30,109 DEBUG matplotlib CONFIGDIR=C:\Users\karth\.matplotlib
2023-05-19 19:48:30,110 DEBUG matplotlib interactive is False
2023-05-19 19:48:30,111 DEBUG matplotlib platform is win32
2023-05-19 19:48:30,126 DEBUG graphviz._tools deprecate positional args: graphviz.backend.piping.pipe(['renderer', 'formatter', 'neato_no_op', 'quiet'])
2023-05-19 19:48:30,127 DEBUG graphviz._tools deprecate positional args: graphviz.backend.rendering.render(['renderer', 'formatter', 'neato_no_op', 'quiet'])
2023-05-19 19:48:30,129 DEBUG graphviz._tools deprecate positional args: graphviz.backend.unflattening.unflatten(['stagger', 'fanout', 'chain', 'encoding'])
2023-05-19 19:48:30,129 DEBUG graphviz._tools deprecate positional args: graphviz.backend.viewing.view(['quiet'])
2023-05-19 19:48:30,133 DEBUG graphviz._tools deprecate positional args: graphviz.quoting.quote(['is_html_string', 'is_valid_id', 'dot_keywords', 'endswith_odd_number_of_backslashes', 'escape_unescaped_quotes'])
2023-05-19 19:48:30,133 DEBUG graphviz._tools deprecate positional args: graphviz.quoting.a_list(['kwargs', 'attributes'])
2023-05-19 19:48:30,133 DEBUG graphviz._tools deprecate positional args: graphviz.quoting.attr_list(['kwargs', 'attributes'])
2023-05-19 19:48:30,134 DEBUG graphviz._tools deprecate positional args: graphviz.dot.Dot.clear(['keep_attrs'])
2023-05-19 19:48:30,134 DEBUG graphviz._tools deprecate positional args: graphviz.dot.Dot.__iter__(['subgraph'])
2023-05-19 19:48:30,134 DEBUG graphviz._tools deprecate positional args: graphviz.dot.Dot.node(['_attributes'])
2023-05-19 19:48:30,134 DEBUG graphviz._tools deprecate positional args: graphviz.dot.Dot.edge(['_attributes'])
2023-05-19 19:48:30,134 DEBUG graphviz._tools deprecate positional args: graphviz.dot.Dot.attr(['_attributes'])
2023-05-19 19:48:30,134 DEBUG graphviz._tools deprecate positional args: graphviz.dot.Dot.subgraph(['name', 'comment', 'graph_attr', 'node_attr', 'edge_attr', 'body'])
2023-05-19 19:48:30,135 DEBUG graphviz._tools deprecate positional args: graphviz.piping.Pipe._pipe_legacy(['renderer', 'formatter', 'neato_no_op', 'quiet'])
2023-05-19 19:48:30,136 DEBUG graphviz._tools deprecate positional args: graphviz.saving.Save.save(['directory'])
2023-05-19 19:48:30,136 DEBUG graphviz._tools deprecate positional args: graphviz.rendering.Render.render(['directory', 'view', 'cleanup', 'format', 'renderer', 'formatter', 'neato_no_op', 'quiet', 'quiet_view'])
2023-05-19 19:48:30,136 DEBUG graphviz._tools deprecate positional args: graphviz.rendering.Render.view(['directory', 'cleanup', 'quiet', 'quiet_view'])
2023-05-19 19:48:30,137 DEBUG graphviz._tools deprecate positional args: graphviz.unflattening.Unflatten.unflatten(['stagger', 'fanout', 'chain'])
2023-05-19 19:48:30,137 DEBUG graphviz._tools deprecate positional args: graphviz.graphs.BaseGraph.__init__(['comment', 'filename', 'directory', 'format', 'engine', 'encoding', 'graph_attr', 'node_attr', 'edge_attr', 'body', 'strict'])
2023-05-19 19:48:30,138 DEBUG graphviz._tools deprecate positional args: graphviz.sources.Source.from_file(['directory', 'format', 'engine', 'encoding', 'renderer', 'formatter'])
2023-05-19 19:48:30,138 DEBUG graphviz._tools deprecate positional args: graphviz.sources.Source.__init__(['filename', 'directory', 'format', 'engine', 'encoding'])
2023-05-19 19:48:30,138 DEBUG graphviz._tools deprecate positional args: graphviz.sources.Source.save(['directory'])
2023-05-19 19:48:31,764 INFO root Data ingestion started
2023-05-19 19:48:31,764 INFO root Dataframe created
2023-05-19 19:48:32,466 INFO root Data ingestion ended
2023-05-19 19:48:32,466 INFO root Data Transformation started
2023-05-19 19:48:32,466 INFO root Calling the ingestion .csv file and Creating a Dataframe 
2023-05-19 19:48:32,491 INFO root Transforming Brand Name
2023-05-19 19:48:32,498 INFO root Transforming Processor 
2023-05-19 19:48:32,503 INFO root Transforming RAM 
2023-05-19 19:48:32,504 INFO root Transforming OS 
2023-05-19 19:48:32,505 INFO root Transforming Storage 
2023-05-19 19:48:32,506 INFO root Transforming Prices 
2023-05-19 19:48:32,521 INFO root Data Transformation ended
2023-05-19 19:48:32,523 INFO root Data Pre_processing started
2023-05-19 19:48:32,523 INFO root Calling the pre-processing .csv file and Creating a Dataframe 
2023-05-19 19:48:32,544 INFO root Naming the columns
2023-05-19 19:48:32,545 INFO root Deleting the rows with count less than 5
2023-05-19 19:48:32,546 INFO root Data information
2023-05-19 19:48:32,546 INFO root  Row :- 1470, Columns:- 6
2023-05-19 19:48:32,551 INFO root Missing Data Number :- brand_name          0
processor_brand    31
ram                 0
os                 33
storage            41
prices             25
dtype: int64
2023-05-19 19:48:32,552 INFO root Missing Data Percentage :- brand_name        0.00
processor_brand   2.11
ram               0.00
os                2.24
storage           2.79
prices            1.70
dtype: float64%
2023-05-19 19:48:32,553 INFO root Index(['Column Namesbrand_name', 'Column Namesprocessor_brand',
       'Column Namesram', 'Column Namesos', 'Column Namesstorage',
       'Column Namesprices'],
      dtype='object')
2023-05-19 19:48:32,553 INFO root Converting Categorical to Numerical
2023-05-19 19:48:32,553 INFO root brand_name Started:- 
2023-05-19 19:48:32,578 INFO root brand_nameEnded ....
2023-05-19 19:48:32,586 INFO root processor_brand Started:- 
2023-05-19 19:48:32,668 INFO root processor_brandEnded ....
2023-05-19 19:48:32,680 INFO root ram Started:- 
2023-05-19 19:48:32,705 INFO root ramEnded ....
2023-05-19 19:48:32,710 INFO root os Started:- 
2023-05-19 19:48:32,736 INFO root osEnded ....
2023-05-19 19:48:32,745 INFO root storage Started:- 
2023-05-19 19:48:32,794 INFO root storageEnded ....
2023-05-19 19:48:32,806 INFO root Taking out null values
2023-05-19 19:48:32,807 INFO root drop the prices
2023-05-19 19:48:32,813 INFO root Imputing the Missing values
2023-05-19 19:48:32,830 INFO root After Imputing the missing values ..............
2023-05-19 19:48:32,830 INFO root  Row :- 1445, Columns:- 6
2023-05-19 19:48:32,831 INFO root Missing Data Number :- brand_name         0
processor_brand    0
ram                0
os                 0
storage            0
prices             0
dtype: int64
2023-05-19 19:48:32,833 INFO root Missing Data Percentage :- brand_name        0.00
processor_brand   0.00
ram               0.00
os                0.00
storage           0.00
prices            0.00
dtype: float64%
2023-05-19 19:48:32,842 INFO root Data Pre-Processing ended
2023-05-19 19:48:32,842 INFO root Data Seprated started
2023-05-19 19:48:32,843 INFO root Seprate x and y data
2023-05-19 19:48:32,856 INFO root Scaling the values
2023-05-19 19:48:32,860 INFO root Spliting the data into 80-20
2023-05-19 19:48:32,866 INFO root Data Seprated ended
2023-05-19 19:48:36,655 INFO root Model_analysis started
2023-05-19 19:48:42,390 DEBUG matplotlib CACHEDIR=C:\Users\karth\.matplotlib
2023-05-19 19:48:42,393 DEBUG matplotlib.font_manager Using fontManager instance from C:\Users\karth\.matplotlib\fontlist-v330.json
2023-05-19 19:48:44,827 DEBUG root initializing neural network...
2023-05-19 19:48:44,827 DEBUG root initialized
2023-05-19 19:49:03,716 INFO root Sttoring the model Object
2023-05-19 19:49:03,717 INFO root Model_analysis ended
2023-05-19 19:49:03,731 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-05-19 19:49:03,731 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-05-19 19:49:15,940 ERROR Flask_LaptopPricePrediction.app Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\karth\OneDrive\Documents\Laptop_Price_Prediction_Project\Flask_LaptopPricePrediction\app.py", line 31, in index
    processor_brand=pd.Dataframe(json_data['processor_brand'])
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\pandas\__init__.py", line 264, in __getattr__
    raise AttributeError(f"module 'pandas' has no attribute '{name}'")
AttributeError: module 'pandas' has no attribute 'Dataframe'
2023-05-19 19:49:15,969 INFO werkzeug 127.0.0.1 - - [19/May/2023 19:49:15] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-05-19 19:49:25,716 ERROR Flask_LaptopPricePrediction.app Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\karth\OneDrive\Documents\Laptop_Price_Prediction_Project\Flask_LaptopPricePrediction\app.py", line 31, in index
    processor_brand=pd.Dataframe(json_data['processor_brand'])
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\pandas\__init__.py", line 264, in __getattr__
    raise AttributeError(f"module 'pandas' has no attribute '{name}'")
AttributeError: module 'pandas' has no attribute 'Dataframe'
2023-05-19 19:49:25,719 INFO werkzeug 127.0.0.1 - - [19/May/2023 19:49:25] "[35m[1mGET / HTTP/1.1[0m" 500 -
