2023-05-19 20:14:41,092 DEBUG matplotlib matplotlib data path: C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\matplotlib\mpl-data
2023-05-19 20:14:41,097 DEBUG matplotlib CONFIGDIR=C:\Users\karth\.matplotlib
2023-05-19 20:14:41,098 DEBUG matplotlib interactive is False
2023-05-19 20:14:41,098 DEBUG matplotlib platform is win32
2023-05-19 20:14:41,120 DEBUG graphviz._tools deprecate positional args: graphviz.backend.piping.pipe(['renderer', 'formatter', 'neato_no_op', 'quiet'])
2023-05-19 20:14:41,122 DEBUG graphviz._tools deprecate positional args: graphviz.backend.rendering.render(['renderer', 'formatter', 'neato_no_op', 'quiet'])
2023-05-19 20:14:41,124 DEBUG graphviz._tools deprecate positional args: graphviz.backend.unflattening.unflatten(['stagger', 'fanout', 'chain', 'encoding'])
2023-05-19 20:14:41,125 DEBUG graphviz._tools deprecate positional args: graphviz.backend.viewing.view(['quiet'])
2023-05-19 20:14:41,129 DEBUG graphviz._tools deprecate positional args: graphviz.quoting.quote(['is_html_string', 'is_valid_id', 'dot_keywords', 'endswith_odd_number_of_backslashes', 'escape_unescaped_quotes'])
2023-05-19 20:14:41,129 DEBUG graphviz._tools deprecate positional args: graphviz.quoting.a_list(['kwargs', 'attributes'])
2023-05-19 20:14:41,130 DEBUG graphviz._tools deprecate positional args: graphviz.quoting.attr_list(['kwargs', 'attributes'])
2023-05-19 20:14:41,130 DEBUG graphviz._tools deprecate positional args: graphviz.dot.Dot.clear(['keep_attrs'])
2023-05-19 20:14:41,130 DEBUG graphviz._tools deprecate positional args: graphviz.dot.Dot.__iter__(['subgraph'])
2023-05-19 20:14:41,130 DEBUG graphviz._tools deprecate positional args: graphviz.dot.Dot.node(['_attributes'])
2023-05-19 20:14:41,130 DEBUG graphviz._tools deprecate positional args: graphviz.dot.Dot.edge(['_attributes'])
2023-05-19 20:14:41,130 DEBUG graphviz._tools deprecate positional args: graphviz.dot.Dot.attr(['_attributes'])
2023-05-19 20:14:41,130 DEBUG graphviz._tools deprecate positional args: graphviz.dot.Dot.subgraph(['name', 'comment', 'graph_attr', 'node_attr', 'edge_attr', 'body'])
2023-05-19 20:14:41,132 DEBUG graphviz._tools deprecate positional args: graphviz.piping.Pipe._pipe_legacy(['renderer', 'formatter', 'neato_no_op', 'quiet'])
2023-05-19 20:14:41,134 DEBUG graphviz._tools deprecate positional args: graphviz.saving.Save.save(['directory'])
2023-05-19 20:14:41,134 DEBUG graphviz._tools deprecate positional args: graphviz.rendering.Render.render(['directory', 'view', 'cleanup', 'format', 'renderer', 'formatter', 'neato_no_op', 'quiet', 'quiet_view'])
2023-05-19 20:14:41,134 DEBUG graphviz._tools deprecate positional args: graphviz.rendering.Render.view(['directory', 'cleanup', 'quiet', 'quiet_view'])
2023-05-19 20:14:41,135 DEBUG graphviz._tools deprecate positional args: graphviz.unflattening.Unflatten.unflatten(['stagger', 'fanout', 'chain'])
2023-05-19 20:14:41,135 DEBUG graphviz._tools deprecate positional args: graphviz.graphs.BaseGraph.__init__(['comment', 'filename', 'directory', 'format', 'engine', 'encoding', 'graph_attr', 'node_attr', 'edge_attr', 'body', 'strict'])
2023-05-19 20:14:41,136 DEBUG graphviz._tools deprecate positional args: graphviz.sources.Source.from_file(['directory', 'format', 'engine', 'encoding', 'renderer', 'formatter'])
2023-05-19 20:14:41,136 DEBUG graphviz._tools deprecate positional args: graphviz.sources.Source.__init__(['filename', 'directory', 'format', 'engine', 'encoding'])
2023-05-19 20:14:41,136 DEBUG graphviz._tools deprecate positional args: graphviz.sources.Source.save(['directory'])
2023-05-19 20:14:44,673 INFO root Data ingestion started
2023-05-19 20:14:44,673 INFO root Dataframe created
2023-05-19 20:14:46,499 INFO root Data ingestion ended
2023-05-19 20:14:46,500 INFO root Data Transformation started
2023-05-19 20:14:46,500 INFO root Calling the ingestion .csv file and Creating a Dataframe 
2023-05-19 20:14:46,536 INFO root Transforming Brand Name
2023-05-19 20:14:46,561 INFO root Transforming Processor 
2023-05-19 20:14:46,573 INFO root Transforming RAM 
2023-05-19 20:14:46,579 INFO root Transforming OS 
2023-05-19 20:14:46,582 INFO root Transforming Storage 
2023-05-19 20:14:46,588 INFO root Transforming Prices 
2023-05-19 20:14:46,618 INFO root Data Transformation ended
2023-05-19 20:14:46,619 INFO root Data Pre_processing started
2023-05-19 20:14:46,619 INFO root Calling the pre-processing .csv file and Creating a Dataframe 
2023-05-19 20:14:46,653 INFO root Naming the columns
2023-05-19 20:14:46,656 INFO root Deleting the rows with count less than 5
2023-05-19 20:14:46,656 INFO root Data information
2023-05-19 20:14:46,656 INFO root  Row :- 1470, Columns:- 6
2023-05-19 20:14:46,665 INFO root Missing Data Number :- brand_name          0
processor_brand    31
ram                 0
os                 33
storage            41
prices             25
dtype: int64
2023-05-19 20:14:46,666 INFO root Missing Data Percentage :- brand_name        0.00
processor_brand   2.11
ram               0.00
os                2.24
storage           2.79
prices            1.70
dtype: float64%
2023-05-19 20:14:46,667 INFO root Index(['Column Namesbrand_name', 'Column Namesprocessor_brand',
       'Column Namesram', 'Column Namesos', 'Column Namesstorage',
       'Column Namesprices'],
      dtype='object')
2023-05-19 20:14:46,667 INFO root Converting Categorical to Numerical
2023-05-19 20:14:46,669 INFO root brand_name Started:- 
2023-05-19 20:14:46,742 INFO root brand_nameEnded ....
2023-05-19 20:14:46,829 INFO root processor_brand Started:- 
2023-05-19 20:14:47,111 INFO root processor_brandEnded ....
2023-05-19 20:14:47,161 INFO root ram Started:- 
2023-05-19 20:14:47,240 INFO root ramEnded ....
2023-05-19 20:14:47,261 INFO root os Started:- 
2023-05-19 20:14:47,341 INFO root osEnded ....
2023-05-19 20:14:47,359 INFO root storage Started:- 
2023-05-19 20:14:47,516 INFO root storageEnded ....
2023-05-19 20:14:47,556 INFO root Taking out null values
2023-05-19 20:14:47,559 INFO root drop the prices
2023-05-19 20:14:47,566 INFO root Imputing the Missing values
2023-05-19 20:14:47,605 INFO root After Imputing the missing values ..............
2023-05-19 20:14:47,606 INFO root  Row :- 1445, Columns:- 6
2023-05-19 20:14:47,609 INFO root Missing Data Number :- brand_name         0
processor_brand    0
ram                0
os                 0
storage            0
prices             0
dtype: int64
2023-05-19 20:14:47,610 INFO root Missing Data Percentage :- brand_name        0.00
processor_brand   0.00
ram               0.00
os                0.00
storage           0.00
prices            0.00
dtype: float64%
2023-05-19 20:14:47,626 INFO root Data Pre-Processing ended
2023-05-19 20:14:47,628 INFO root Data Seprated started
2023-05-19 20:14:47,628 INFO root Seprate x and y data
2023-05-19 20:14:47,651 INFO root Scaling the values
2023-05-19 20:14:47,662 INFO root Spliting the data into 80-20
2023-05-19 20:14:47,667 INFO root Data Seprated ended
2023-05-19 20:15:05,479 INFO root Model_analysis started
2023-05-19 20:15:13,167 DEBUG matplotlib CACHEDIR=C:\Users\karth\.matplotlib
2023-05-19 20:15:13,173 DEBUG matplotlib.font_manager Using fontManager instance from C:\Users\karth\.matplotlib\fontlist-v330.json
2023-05-19 20:15:15,734 DEBUG root initializing neural network...
2023-05-19 20:15:15,734 DEBUG root initialized
2023-05-19 20:15:33,083 INFO root Sttoring the model Object
2023-05-19 20:15:33,086 INFO root Model_analysis ended
2023-05-19 20:15:33,149 INFO werkzeug [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-05-19 20:15:33,149 INFO werkzeug [33mPress CTRL+C to quit[0m
2023-05-19 20:15:33,260 ERROR Flask_LaptopPricePrediction.app Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\karth\OneDrive\Documents\Laptop_Price_Prediction_Project\Flask_LaptopPricePrediction\app.py", line 36, in index
    return render_template('index.html',processor_brand=processor_brand,brand_name=brand_name,memory=memory,storage=storage,os=os)
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\karth\OneDrive\Documents\Laptop_Price_Prediction_Project\Flask_LaptopPricePrediction\templates\index.html", line 65, in top-level template code
    {%for index, row in ram.iterrows():%}
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'ram' is undefined
2023-05-19 20:15:33,265 INFO werkzeug 127.0.0.1 - - [19/May/2023 20:15:33] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-05-19 20:15:35,969 ERROR Flask_LaptopPricePrediction.app Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\karth\OneDrive\Documents\Laptop_Price_Prediction_Project\Flask_LaptopPricePrediction\app.py", line 36, in index
    return render_template('index.html',processor_brand=processor_brand,brand_name=brand_name,memory=memory,storage=storage,os=os)
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\karth\OneDrive\Documents\Laptop_Price_Prediction_Project\Flask_LaptopPricePrediction\templates\index.html", line 65, in top-level template code
    {%for index, row in ram.iterrows():%}
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'ram' is undefined
2023-05-19 20:15:35,971 INFO werkzeug 127.0.0.1 - - [19/May/2023 20:15:35] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-05-19 20:15:37,808 ERROR Flask_LaptopPricePrediction.app Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\karth\OneDrive\Documents\Laptop_Price_Prediction_Project\Flask_LaptopPricePrediction\app.py", line 36, in index
    return render_template('index.html',processor_brand=processor_brand,brand_name=brand_name,memory=memory,storage=storage,os=os)
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\karth\OneDrive\Documents\Laptop_Price_Prediction_Project\Flask_LaptopPricePrediction\templates\index.html", line 65, in top-level template code
    {%for index, row in ram.iterrows():%}
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'ram' is undefined
2023-05-19 20:15:37,811 INFO werkzeug 127.0.0.1 - - [19/May/2023 20:15:37] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-05-19 20:17:21,545 ERROR Flask_LaptopPricePrediction.app Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\karth\OneDrive\Documents\Laptop_Price_Prediction_Project\Flask_LaptopPricePrediction\app.py", line 36, in index
    return render_template('index.html',processor_brand=processor_brand,brand_name=brand_name,memory=memory,storage=storage,os=os)
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\karth\OneDrive\Documents\Laptop_Price_Prediction_Project\Flask_LaptopPricePrediction\templates\index.html", line 65, in top-level template code
    {%for index, row in ram.iterrows():%}
  File "C:\Users\karth\AppData\Roaming\Python\Python310\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'ram' is undefined
2023-05-19 20:17:21,547 INFO werkzeug 127.0.0.1 - - [19/May/2023 20:17:21] "[35m[1mGET / HTTP/1.1[0m" 500 -
